export const VALIDATE_FORM = "VALIDATE_FORM";
export const VALIDATE_FORM_SUCCESS = "VALIDATE_FORM_SUCCESS";
export const VALIDATE_FORM_FAIL = "VALIDATE_FORM_FAIL";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
